name: "hello-user-pstr"
limit: 1000
memory_size: 0x1000
input_streams:
  0x80: [65, 108, 105, 99, 101, 10]
  0x84: []
reports:
  # - name: Log
  #   slice: all
  #   view: |
  #     T {T0:hex} {T1:hex} {T2:hex} {T3:hex}
  #     A {A0:hex} {A1:hex} {A2:hex} {A3:hex}
  #     S {S0Fp:hex} {S1:hex} {S2:hex} {S3:hex}
  #     {memory:0:31}
  #     {pc}:	{instruction}	{pc:label}
  - name: Check results
    slice: last
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
      symio[0x80]: {io:0x80:sym}
      symio[0x84]: {io:0x84:sym}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [87,104,97,116,32,105,115,32,121,111,117,114,32,110,97,109,101,63,10,72,101,108,108,111,44,32,65,108,105,99,101,33]
      symio[0x80]: "" >>> ""
      symio[0x84]: "" >>> "What is your name?\nHello, Alice!"
